### ISSUE TITLE
new repo

### ISSUE THREAD

**Issue by ryandeussing** [tristanoneil/lifeinbtv-old#1]
Hi Tristan, I came across your lifeinbtv.com site a while back, bookmarked it, and recently started planning something similar to post and share videos of my daughter with family.

I see you've deployed a new version using Gatsby and 'self-hosted' video. I'm interested in doing much the same.

Would you consider sharing the code for your rebuilt site? Even if it's just a readme with info about the decisions you made it would give me a huge head start. 

Thanks in advance!

**Comment by tristanoneil** [comment]
@ryandeussing I'm glad to see I've started a trend 😆 

You can see the source for the Gatsby site [here](https://github.com/tristanoneil/lifeinbtv). It's based on the [starter blog](https://github.com/gatsbyjs/gatsby-starter-blog).

I actually built this new site in Jekykll first and then opted for Gatsby because I've been meaning to give it a shot and its ability to easily lazy load images and [preload](https://www.gatsbyjs.org/docs/gatsby-link/) other pages really enticed me. The site itself is hosted on [Netlify](https://www.netlify.com).

I was hosting on Vimeo previously but one of my videos was taken down by a copyright holder  (Vimeo just deletes the video, which is fun). These videos are in a fair use gray area (given 99% of the people that watch them are friends and family) so to protect myself moving forward from randomly having them deleted I decided to "self host". You could go the route of just encoding a H264 video and using a `video` tag which would work OK for most people but I opted for using [HLS](https://en.wikipedia.org/wiki/HTTP_Live_Streaming) to support my lower bandwidth family members. I initially used [AWS Elastic Transcoder](https://aws.amazon.com/elastictranscoder/) to encode the videos into an HLS format and hosted on S3 which works really well but I've been trying to avoid Amazon lately (for principled reasons) so moving forward I'll likely encode locally using [this helpful script](https://github.com/bentasker/HLS-Stream-Creator) and host with [B2 from Backblaze](https://www.backblaze.com/b2/cloud-storage.html).

Clientside I'm using [hls.js](https://github.com/video-dev/hls.js/) to support HLS streaming in browsers that don't natively support it and [Plyr](https://plyr.io) to provide a consistent video UI across browsers.

Hopefully this helps. Good luck with your project!

**Comment by ryandeussing** [comment]
Thanks a ton!

**Comment by ryandeussing** [comment]
I believe [the new repo](https://github.com/tristanoneil/lifeinbtv) may be private?

**Comment by ryandeussing** [comment]
@tristanoneil just a ping re ☝️
